import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const Header = dynamic(() => import("./components/Header"), { ssr: false });
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Omin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Header links={[{label:"Home", path:"/"}, {label:"Opportunities", path:"/opportunities/allOpportunities/"}, {label:"About Us", path:"/"}, {label:"Blogs", path:"/"}]} /> */}
        {children}
      </body>
    </html>
  );
}
